### ISSUE TITLE
@media parsing error

### ISSUE THREAD

**Issue by katie1348** [sibiraj-s/vscode-scss-formatter#11]
I have the following in my SASS:

`  @media screen and (max-width : 735px) and #{breakpoint(medium)}  {
    line-height: 120%;
  }
`

The syntax highlighter puts a RED underline on the # and gives the following error:

( expectedscss(css-lparentexpected)

I don't know if this is a problem with the sass formatter or somewhere else, so I am starting here.

The SASS is of course perfectly fine, compiles and works as expected.

**Comment by sibiraj-s** [comment]
Hi, This Formatter doesn't provide Intellisense, just formatting and the errors are shown in the statusbar of vscode. I am pretty sure it is by something else.
