### ISSUE TITLE
CSS variables in rgba don't works

### ISSUE THREAD

**Issue by hugo-levet** [sibiraj-s/vscode-scss-formatter#14]
```
:root{
    --shadow-color: #000000;
    --elevation-shadow: 0 2px 6px 2px rgba(var(--shadow-color), 0.15), 0 2px 1px 0px rgba(var(--shadow-color), 0.3);`
}
```
Throw an error for compile but works in CSS

**Comment by sibiraj-s** [comment]
Hi, It looks like an issue with prettier. This extension uses prettier under the hood to format files.

See [Prettier Playground demo](https://prettier.io/playground/#N4Igxg9gdgLgprEAuZAnCEbADpQAQF4C0RAzgBYCGAJhAO5GQA2EqSeAxAAw+8DcuQsSJwmcAG6UYAS2hkqtOuy54ATAAcAHngBsWtftQBzAEaUAFJNTmSFGvUYQWqAJQAaPFwB0ARgCs7p4G2j76XIamFlY28vYMzKyB3gDMLnwABrgAviBuIBDqMtCkyKCUqOh0AArlCCUolEx0lACeJXkmqJRgANZwMADKlAC2cAAy0lBwyABmjaRwHV29-QPq3ZNGyDCoAK6LIHDDJnDU1KdjlFBGu5RGcABirMNSMtfIIJS7MBC5IOQwYZMADq5Gk8FI6zAcAGdXB0nE4JaHzApHaIEmC1QMCqXSML1m8wOACtSJoBpsxABFXaYaZIOZMBZ5daoLEfUio9HqVCTGDA6TUGDkZAADi4LPQC2BXXUHx5cCx4mmeQAjrT4LiCvVPqQiFNTqc-qg4OrpCbcXcCQyiXkFsNpNs9gdSJS4DS6YSmQcYJQTAKhSKkKo8jtKNImJsAMIQYbWw6kPx-XYLAAqfvqjOZIHE+wAklBzrABmBeYUAIKFgYwFpiL0LLJZIA)

Also there is a back quote at the end of line3 after the semi colon. Try removing that.

Closing the issue for now. Feel free to continue the discussion if required.
