### ISSUE TITLE
Error coming on formatting scss file with scss-formatter

### ISSUE THREAD

**Issue by ankurraj2606** [sibiraj-s/vscode-scss-formatter#18]
sass-convert' is not recognized as an internal or external command,
operable program or batch file.

**Comment by sibiraj-s** [comment]
I am not sure if this error is from this extension. There is no such command as `sass-convert`. Can you re-verify it once?

**Comment by sibiraj-s** [comment]
Closing this issue for now. Feel free to reopen with more info if you still think this problem is with this extension. Thank you
